package rsd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-12-26T10:55:55.012+01:00
 * Generated source version: 3.4.7
 *
 */
@WebServiceClient(name = "StatelessBeanService",
                  wsdlLocation = "http://localhost:8080/DrzavaEJB/StatelessBean?wsdl",
                  targetNamespace = "http://rzk/")
public class StatelessBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rzk/", "StatelessBeanService");
    public final static QName StatelessBeanPort = new QName("http://rzk/", "StatelessBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/DrzavaEJB/StatelessBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatelessBeanService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/DrzavaEJB/StatelessBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatelessBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatelessBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatelessBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StatelessBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StatelessBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StatelessBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StatelessBeanRemote
     */
    @WebEndpoint(name = "StatelessBeanPort")
    public StatelessBeanRemote getStatelessBeanPort() {
        return super.getPort(StatelessBeanPort, StatelessBeanRemote.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatelessBeanRemote
     */
    @WebEndpoint(name = "StatelessBeanPort")
    public StatelessBeanRemote getStatelessBeanPort(WebServiceFeature... features) {
        return super.getPort(StatelessBeanPort, StatelessBeanRemote.class, features);
    }

}
