package rsd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-12-26T10:55:54.981+01:00
 * Generated source version: 3.4.7
 *
 */
@WebService(targetNamespace = "http://rzk/", name = "StatelessBeanRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface StatelessBeanRemote {

    @WebMethod
    @RequestWrapper(localName = "resolve", targetNamespace = "http://rzk/", className = "rsd.Resolve")
    @ResponseWrapper(localName = "resolveResponse", targetNamespace = "http://rzk/", className = "rsd.ResolveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String resolve(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
